name: Generate Go Code from Proto

on:
  push:
    branches:
      - main  

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Generated Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Protoc & Go Plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/Farida2025/assignment2-protos.git proto-repo

      - name: Generate Go Code
        run: |
          mkdir -p order payment
          protoc --proto_path=proto-repo/proto \
            --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            proto-repo/proto/*.proto

      - name: Push Generated Code
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Auto-generate gRPC code" || exit 0
          git push origin main
